version: '3.9'
networks:
  default:
    name: 'jet'
services:
  service:
    container_name: 'delivery'
    build: './services/delivery'
    restart: unless-stopped
    # depends_on:
    #   - redis
    ports:
      - '${API_HTTP_PORT:-3030}:3030'
    environment:
      # REDIS_HOST: 'jet-redis'
      # REDIS_PORT: '${REDIS_PORT:-6379}'
      API_HTTP_PORT: '${API_HTTP_PORT:-3030}'

  operator-ui:
    container_name: 'operator-ui'
    build: './apps/operator'
    restart: unless-stopped
    depends_on:
      - service
    ports:
      - '${OPERATOR_UI_PORT:-3000}:3000'
    environment:
      NODE_OPTIONS: '--max-old-space-size=2048'
      DATA_ROOT: '/public'
      # CONDUIT_SERVER: 'delivery:${CORE_GRPC_PORT:-55152}'

  shop-ui:
    container_name: 'shop-ui'
    build: './apps/shop'
    restart: unless-stopped
    depends_on:
      - service
    ports:
      - '${SHOP_UI_PORT:-3001}:3000'
    environment:
      NODE_OPTIONS: '--max-old-space-size=2048'
      DATA_ROOT: '/public'
      # CONDUIT_SERVER: 'delivery:${CORE_GRPC_PORT:-55152}'

  # Dependencies
  redis:
    container_name: 'jet-redis'
    image: 'redis:latest'
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    environment:
      REDIS_PASSWORD: '${REDIS_PASS:-pass}'

  mongodb:
    container_name: 'jet-mongo'
    image: 'mongo:latest'
    restart: unless-stopped
    ports:
      - '${DB_PORT:-27017}:27017'
    environment:
      MONGO_INITDB_DATABASE: 'delivery'
      MONGO_INITDB_ROOT_USERNAME: '${DB_USER:-jet}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASS:-pass}'
    volumes:
      - mongo:/data/db
# DB_CONN_URI: '${DB_CONN_URI:-mongodb://conduit:pass@conduit-mongo:27017/conduit?authSource=admin}'

# Persistent Volumes
volumes:
  mongo:
    external: false
